import {JSONSchema6} from 'json-schema';

const EOL = '\n';
const TAG_NAMES_FIELD = 'x-navtitle';
const BLOCK = EOL.repeat(2);
const INFO_TAB_NAME = 'Info';
const SANDBOX_TAB_NAME = 'Sandbox';
const CONTACTS_SECTION_NAME = 'Contacts';
const TAGS_SECTION_NAME = 'Sections';
const ENDPOINTS_SECTION_NAME = 'Endpoints';
const REQUEST_SECTION_NAME = 'Request';
const PATH_PARAMETERS_SECTION_NAME = 'Path parameters';
const HEADERS_SECTION_NAME = 'Headers';
const QUERY_PARAMETERS_SECTION_NAME = 'Query parameters';
const COOKIES_SECTION_NAME = 'Cookies';
const RESPONSES_SECTION_NAME = 'Responses';
const HTML_COMMENTS_OPEN_DIRECTIVE = '<!--';
const HTML_COMMENTS_CLOSE_DIRECTIVE = '-->';
const DISABLE_LINTER_DIRECTIVE = 'markdownlint-disable-file';
const SPEC_RENDER_MODE_DEFAULT = 'inline';
const SPEC_RENDER_MODE_HIDDEN = 'hidden';
const SPEC_SECTION_NAME = 'Specification';
const SPEC_SECTION_TYPE = 'Open API';

const PRIMITIVE_JSON6_SCHEMA_TYPES =
    new Set<JSONSchema6['type']>(['string', 'boolean', 'null', 'number', 'integer']);
const SUPPORTED_ENUM_TYPES = ['string', 'number'] as const;

export {
    TAG_NAMES_FIELD,
    BLOCK,
    INFO_TAB_NAME,
    SANDBOX_TAB_NAME,
    CONTACTS_SECTION_NAME,
    TAGS_SECTION_NAME,
    ENDPOINTS_SECTION_NAME,
    REQUEST_SECTION_NAME,
    PATH_PARAMETERS_SECTION_NAME,
    HEADERS_SECTION_NAME,
    QUERY_PARAMETERS_SECTION_NAME,
    COOKIES_SECTION_NAME,
    RESPONSES_SECTION_NAME,
    EOL,
    HTML_COMMENTS_OPEN_DIRECTIVE,
    HTML_COMMENTS_CLOSE_DIRECTIVE,
    DISABLE_LINTER_DIRECTIVE,
    SPEC_RENDER_MODE_DEFAULT,
    SPEC_RENDER_MODE_HIDDEN,
    SPEC_SECTION_NAME,
    SPEC_SECTION_TYPE,
    PRIMITIVE_JSON6_SCHEMA_TYPES,
    SUPPORTED_ENUM_TYPES,
};

export default {
    TAG_NAMES_FIELD,
    BLOCK,
    INFO_TAB_NAME,
    SANDBOX_TAB_NAME,
    CONTACTS_SECTION_NAME,
    TAGS_SECTION_NAME,
    ENDPOINTS_SECTION_NAME,
    REQUEST_SECTION_NAME,
    PATH_PARAMETERS_SECTION_NAME,
    HEADERS_SECTION_NAME,
    QUERY_PARAMETERS_SECTION_NAME,
    COOKIES_SECTION_NAME,
    RESPONSES_SECTION_NAME,
    EOL,
    HTML_COMMENTS_OPEN_DIRECTIVE,
    HTML_COMMENTS_CLOSE_DIRECTIVE,
    DISABLE_LINTER_DIRECTIVE,
    SPEC_RENDER_MODE_DEFAULT,
    SPEC_RENDER_MODE_HIDDEN,
    SPEC_SECTION_NAME,
    SPEC_SECTION_TYPE,
    PRIMITIVE_JSON6_SCHEMA_TYPES,
    SUPPORTED_ENUM_TYPES,
};
