const EOL = '\n';
const TAG_NAMES_FIELD = 'x-navtitle';
const BLOCK = EOL.repeat(2);
const DESCRIPTION_SECTION_NAME = 'Description';
const CONTACTS_SECTION_NAME = 'Contacts';
const TAGS_SECTION_NAME = 'Sections';
const ENDPOINTS_SECTION_NAME = 'Endpoints';
const REQUEST_SECTION_NAME = 'Request';
const PARAMETERS_SECTION_NAME = 'Parameters';
const RESPONSES_SECTION_NAME = 'Responses';

export {TAG_NAMES_FIELD, BLOCK, DESCRIPTION_SECTION_NAME, CONTACTS_SECTION_NAME, TAGS_SECTION_NAME, ENDPOINTS_SECTION_NAME, REQUEST_SECTION_NAME, PARAMETERS_SECTION_NAME, RESPONSES_SECTION_NAME, EOL};

export default {TAG_NAMES_FIELD, BLOCK, DESCRIPTION_SECTION_NAME, CONTACTS_SECTION_NAME, TAGS_SECTION_NAME, ENDPOINTS_SECTION_NAME, REQUEST_SECTION_NAME, PARAMETERS_SECTION_NAME, RESPONSES_SECTION_NAME, EOL};
