name: Bug report
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.

        This issue tracker is for bugs and issues found within packege.

        Please fill in as much of the following form as you're able.
  - type: input
    attributes:
      label: Package version
  - type: input
    attributes:
      label: Node version
      description: |
        Output of `node -v`.
  - type: input
    attributes:
      label: Platform
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: >
        Enter details about your bug, preferably a simple code snippet that can
        be run using without installing third-party dependencies
        or downloading code from the internet.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible please provide screenshots or textual output.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible please provide screenshots or textual output.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
