# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bundle size diff

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**']

jobs:
  build-base:
    name: Build base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}

    - name: Install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: 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

    - name: Build
      run: npm run build-demo

    - name: Upload base stats.json
      uses: actions/upload-artifact@v2
      with:
        name: base
        path: ./demo/demo-dist/stats.json
        retention-days: 1
        
  build-pr:
    name: Build PR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: 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

    - name: Build
      run: npm run build-demo

    - name: Upload base stats.json
      uses: actions/upload-artifact@v2
      with:
        name: pr
        path: ./demo/demo-dist/stats.json
        retention-days: 1
  
  report:
    name: Generate report
    runs-on: ubuntu-latest
    needs: [build-base, build-pr]

    steps:
    - name: Checkout PR
      uses: actions/checkout@v2

    - name: Download base stats
      uses: actions/download-artifact@v2
      with:
        name: base
        path: base

    - name: Download PR stats
      uses: actions/download-artifact@v2
      with:
        name: pr
        path: pr

    - name: Get diff
      id: get-diff
      uses: NejcZdovc/bundle-size-diff@v1
      with:
        base_path: './base/stats.json'
        pr_path: './pr/stats.json'

    - name: Comment
      uses: NejcZdovc/comment-pr@v1.1.1
      with:
        file: 'comment.md'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        OLD: ${{steps.get-diff.outputs.base_file_string}}
        NEW: ${{steps.get-diff.outputs.pr_file_string}}
        DIFF: ${{steps.get-diff.outputs.diff_file_string}}
        DIFF_PERCENT: ${{steps.get-diff.outputs.percent}}


# - name: Bundle size diff
#   # You may pin to the exact commit or the version.
#   # uses: NejcZdovc/bundle-size-diff@5321de41d2d62a7b0f4d6e60f59d1280a0034160
#   uses: NejcZdovc/bundle-size-diff@v1.1.0
#   with:
#     # Path to base stats file
#     base_path: 
#     # Path to PR stats file
#     pr_path: 
#     # Regex that will exclude some assets
#     excluded_assets: # optional

