# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: bundle-stats-action 10_13

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npx webpack --mode production --json static/webpack-stats.json
    
    - name: Run bundle-stats
      uses: vio/bundle-stats-action@v1
      with:
        webpack-stats-path: 'static/webpack-stats.json'
        repo-token: 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
