name: 'Tests: integration'

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [24]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and install dependencies
        uses: diplodoc-platform/setup-node-action@v1
        with:
          node-version: ${{ vars.NODE_VERSION || '24' }}
          registry-url: 'https://registry.npmjs.org'

      - name: Run build
        run: npm run build

      - name: Run e2e tests
        working-directory: tests
        run: npm ci && npm test
