# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "development" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Jest Code Coverage Badge

      uses: luk-schweizer/jest-code-coverage-badge-action@v1.0.1
      with:
        # Command that will execute and collect test coverage data. Should include --coverage option
        test-command: npm run test
